name: Install dependencies
description: "A composite action for installing dependencies"
inputs:
  api-endpoint:
    required: true
  firebase-api-key:
    required: true
  firebase-auth-domain:
    required: true
  firebase-project-id:
    required: true
  firebase-app-id:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Setup .env file
      env:
        VITE_PUBLIC_API_ENDPOINT: ${{ inputs.api-endpoint }}
        VITE_FIREBASE_API_KEY: ${{ inputs.firebase-api-key }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ inputs.firebase-auth-domain }}
        VITE_FIREBASE_PROJECT_ID: ${{ inputs.firebase-project-id }}
        VITE_FIREBASE_APP_ID: ${{ inputs.firebase-app-id }}
      shell: bash
      run: |
        echo "VITE_PUBLIC_API_ENDPOINT=${VITE_PUBLIC_API_ENDPOINT}" >> .env
        echo "VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}" >> .env
        echo "VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}" >> .env
        echo "VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}" >> .env
        echo "VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}" >> .env
