[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]

[build]
  command = "pnpm run build"
  publish = "dist-csr"  
  functions = "dist-ssr"  
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
