[functions]
  node_bundler = "esbuild"
  external_node_modules = ["react", "react-dom"]

[build]
  command = "pnpm build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
