packages:
  - nginx
  - nodejs
  - npm

runcmd:
  - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  - npm install -g pnpm pm2

  # Setup app directory
  - mkdir -p /var/www/lapinlearn-webapp
  - chown -R ubuntu:ubuntu /var/www/lapinlearn-webapp  # Replace $USER with actual default user

  # Configure Nginx
  - |
    cat <<EOF > /etc/nginx/sites-available/default
    server {
      listen 80;
      server_name YOUR_DOMAIN_OR_IP;
    
      location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
      }
    
      error_page 404 /index.html;
    }
    EOF

  - ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
  - systemctl restart nginx
