name: "DigitalOcean Sync"
description: "A composite action to upload files to an DigitalOcean."
runs:
  using: "composite"
  steps:
    - name: Deploy React app
      shell: bash
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
    
        # Copy project to server
        ssh -i ssh_key -o StrictHostKeyChecking=no root@$DROPLET_IP "mkdir -p /var/www/lapinlearn-webapp"
        scp -i ssh_key -o StrictHostKeyChecking=no -r . root@$DROPLET_IP:/var/www/lapinlearn-webapp

        # Install dependencies and start app
        ssh -i ssh_key -o StrictHostKeyChecking=no root@$DROPLET_IP <<EOF
          cd /var/www/lapinlearn-webapp
          pnpm install
          pnpm run build
          pm2 restart all || pm2 start dist-ssr/ssr.js --name lapinlearn-webapp
        EOF
