name: "DigitalOcean Sync"
description: "A composite action to upload files to an DigitalOcean."
inputs:
  ssh-key:
    description: "A private key to connect "
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Droplet IP
      uses: actions/download-artifact@v4
      with:
        name: droplet-ip

    - name: Deploy React app
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh-key }}
      run: |
        DROPLET_IP=$(cat droplet_ip.txt)
        echo "✅ DROPLET_IP is: $DROPLET_IP"
        if [[ -z "$DROPLET_IP" ]]; then
          echo "❌ ERROR: DROPLET_IP is empty!"
          exit 1
        fi
        echo "$SSH_KEY" > ssh_key
        chmod 600 ssh_key
    
        # Install dependencies and start app
        ssh -i ssh_key -o StrictHostKeyChecking=no root@$DROPLET_IP <<EOF
          # Install Node.js and pnpm
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          sudo apt-get install -y nodejs
          npm install -g pnpm pm2
        
          cd /var/www/lapinlearn-webapp
          pnpm install
          pnpm run build
          pm2 restart all || pm2 start dist-ssr/ssr.js --name lapinlearn-webapp
        EOF
