/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AuthenticatedImport } from "./routes/_authenticated";
import { Route as AuthenticatedDashboardImport } from "./routes/_authenticated/_dashboard";
import { Route as AuthenticatedDashboardProfileImport } from "./routes/_authenticated/_dashboard/_profile";
import { Route as AuthenticatedDashboardProfileChangePasswordImport } from "./routes/_authenticated/_dashboard/_profile/change-password";
import { Route as AuthenticatedDashboardProfileHistoryImport } from "./routes/_authenticated/_dashboard/_profile/history";
import { Route as AuthenticatedDashboardProfileProfileImport } from "./routes/_authenticated/_dashboard/_profile/profile";
import { Route as AuthenticatedDashboardContentEditorImport } from "./routes/_authenticated/_dashboard/content-editor";
import { Route as AuthenticatedDashboardPracticeCollectionIdImport } from "./routes/_authenticated/_dashboard/practice/$collectionId";
import { Route as AuthenticatedDashboardPracticeIndexImport } from "./routes/_authenticated/_dashboard/practice/index";
import { Route as AuthenticatedDashboardPracticeSimulatedTestResultImport } from "./routes/_authenticated/_dashboard/practice/simulated-test/result";
import { Route as AuthenticatedIndexImport } from "./routes/_authenticated/index";
import { Route as AuthenticatedPracticeSimulatedTestIndexImport } from "./routes/_authenticated/practice/simulated-test/index";
import { Route as AuthenticatedSpeakingIndexImport } from "./routes/_authenticated/speaking/index";
import { Route as AuthenticationImport } from "./routes/_authentication";
import { Route as AuthenticationForgotPasswordImport } from "./routes/_authentication/forgot-password";
import { Route as AuthenticationLogInImport } from "./routes/_authentication/log-in";
import { Route as AuthenticationResetPasswordImport } from "./routes/_authentication/reset-password";
import { Route as AuthenticationSignUpImport } from "./routes/_authentication/sign-up";
import { Route as AuthenticationVerifyOtpImport } from "./routes/_authentication/verify-otp";

// Create/Update Routes

const AuthenticationRoute = AuthenticationImport.update({
  id: "/_authentication",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedRoute = AuthenticatedImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRoute,
} as any);

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticationVerifyOtpRoute = AuthenticationVerifyOtpImport.update({
  id: "/verify-otp",
  path: "/verify-otp",
  getParentRoute: () => AuthenticationRoute,
} as any);

const AuthenticationSignUpRoute = AuthenticationSignUpImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => AuthenticationRoute,
} as any);

const AuthenticationResetPasswordRoute = AuthenticationResetPasswordImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => AuthenticationRoute,
} as any);

const AuthenticationLogInRoute = AuthenticationLogInImport.update({
  id: "/log-in",
  path: "/log-in",
  getParentRoute: () => AuthenticationRoute,
} as any);

const AuthenticationForgotPasswordRoute = AuthenticationForgotPasswordImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => AuthenticationRoute,
} as any);

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: "/_dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedSpeakingIndexRoute = AuthenticatedSpeakingIndexImport.update({
  id: "/speaking/",
  path: "/speaking/",
  getParentRoute: () => AuthenticatedRoute,
} as any);

const AuthenticatedDashboardContentEditorRoute = AuthenticatedDashboardContentEditorImport.update({
  id: "/content-editor",
  path: "/content-editor",
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);

const AuthenticatedDashboardProfileRoute = AuthenticatedDashboardProfileImport.update({
  id: "/_profile",
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);

const AuthenticatedPracticeSimulatedTestIndexRoute =
  AuthenticatedPracticeSimulatedTestIndexImport.update({
    id: "/practice/simulated-test/",
    path: "/practice/simulated-test/",
    getParentRoute: () => AuthenticatedRoute,
  } as any);

const AuthenticatedDashboardPracticeIndexRoute = AuthenticatedDashboardPracticeIndexImport.update({
  id: "/practice/",
  path: "/practice/",
  getParentRoute: () => AuthenticatedDashboardRoute,
} as any);

const AuthenticatedDashboardPracticeCollectionIdRoute =
  AuthenticatedDashboardPracticeCollectionIdImport.update({
    id: "/practice/$collectionId",
    path: "/practice/$collectionId",
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any);

const AuthenticatedDashboardProfileProfileRoute = AuthenticatedDashboardProfileProfileImport.update(
  {
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any
);

const AuthenticatedDashboardProfileHistoryRoute = AuthenticatedDashboardProfileHistoryImport.update(
  {
    id: "/history",
    path: "/history",
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any
);

const AuthenticatedDashboardProfileChangePasswordRoute =
  AuthenticatedDashboardProfileChangePasswordImport.update({
    id: "/change-password",
    path: "/change-password",
    getParentRoute: () => AuthenticatedDashboardProfileRoute,
  } as any);

const AuthenticatedDashboardPracticeSimulatedTestResultRoute =
  AuthenticatedDashboardPracticeSimulatedTestResultImport.update({
    id: "/practice/simulated-test/result",
    path: "/practice/simulated-test/result",
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedImport;
      parentRoute: typeof rootRoute;
    };
    "/_authentication": {
      id: "/_authentication";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticationImport;
      parentRoute: typeof rootRoute;
    };
    "/_authenticated/_dashboard": {
      id: "/_authenticated/_dashboard";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedDashboardImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authentication/forgot-password": {
      id: "/_authentication/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof AuthenticationForgotPasswordImport;
      parentRoute: typeof AuthenticationImport;
    };
    "/_authentication/log-in": {
      id: "/_authentication/log-in";
      path: "/log-in";
      fullPath: "/log-in";
      preLoaderRoute: typeof AuthenticationLogInImport;
      parentRoute: typeof AuthenticationImport;
    };
    "/_authentication/reset-password": {
      id: "/_authentication/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof AuthenticationResetPasswordImport;
      parentRoute: typeof AuthenticationImport;
    };
    "/_authentication/sign-up": {
      id: "/_authentication/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof AuthenticationSignUpImport;
      parentRoute: typeof AuthenticationImport;
    };
    "/_authentication/verify-otp": {
      id: "/_authentication/verify-otp";
      path: "/verify-otp";
      fullPath: "/verify-otp";
      preLoaderRoute: typeof AuthenticationVerifyOtpImport;
      parentRoute: typeof AuthenticationImport;
    };
    "/_authenticated/": {
      id: "/_authenticated/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/_dashboard/_profile": {
      id: "/_authenticated/_dashboard/_profile";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedDashboardProfileImport;
      parentRoute: typeof AuthenticatedDashboardImport;
    };
    "/_authenticated/_dashboard/content-editor": {
      id: "/_authenticated/_dashboard/content-editor";
      path: "/content-editor";
      fullPath: "/content-editor";
      preLoaderRoute: typeof AuthenticatedDashboardContentEditorImport;
      parentRoute: typeof AuthenticatedDashboardImport;
    };
    "/_authenticated/speaking/": {
      id: "/_authenticated/speaking/";
      path: "/speaking";
      fullPath: "/speaking";
      preLoaderRoute: typeof AuthenticatedSpeakingIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/_dashboard/_profile/change-password": {
      id: "/_authenticated/_dashboard/_profile/change-password";
      path: "/change-password";
      fullPath: "/change-password";
      preLoaderRoute: typeof AuthenticatedDashboardProfileChangePasswordImport;
      parentRoute: typeof AuthenticatedDashboardProfileImport;
    };
    "/_authenticated/_dashboard/_profile/history": {
      id: "/_authenticated/_dashboard/_profile/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof AuthenticatedDashboardProfileHistoryImport;
      parentRoute: typeof AuthenticatedDashboardProfileImport;
    };
    "/_authenticated/_dashboard/_profile/profile": {
      id: "/_authenticated/_dashboard/_profile/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof AuthenticatedDashboardProfileProfileImport;
      parentRoute: typeof AuthenticatedDashboardProfileImport;
    };
    "/_authenticated/_dashboard/practice/$collectionId": {
      id: "/_authenticated/_dashboard/practice/$collectionId";
      path: "/practice/$collectionId";
      fullPath: "/practice/$collectionId";
      preLoaderRoute: typeof AuthenticatedDashboardPracticeCollectionIdImport;
      parentRoute: typeof AuthenticatedDashboardImport;
    };
    "/_authenticated/_dashboard/practice/": {
      id: "/_authenticated/_dashboard/practice/";
      path: "/practice";
      fullPath: "/practice";
      preLoaderRoute: typeof AuthenticatedDashboardPracticeIndexImport;
      parentRoute: typeof AuthenticatedDashboardImport;
    };
    "/_authenticated/practice/simulated-test/": {
      id: "/_authenticated/practice/simulated-test/";
      path: "/practice/simulated-test";
      fullPath: "/practice/simulated-test";
      preLoaderRoute: typeof AuthenticatedPracticeSimulatedTestIndexImport;
      parentRoute: typeof AuthenticatedImport;
    };
    "/_authenticated/_dashboard/practice/simulated-test/result": {
      id: "/_authenticated/_dashboard/practice/simulated-test/result";
      path: "/practice/simulated-test/result";
      fullPath: "/practice/simulated-test/result";
      preLoaderRoute: typeof AuthenticatedDashboardPracticeSimulatedTestResultImport;
      parentRoute: typeof AuthenticatedDashboardImport;
    };
  }
}

// Create and export the route tree

interface AuthenticatedDashboardProfileRouteChildren {
  AuthenticatedDashboardProfileChangePasswordRoute: typeof AuthenticatedDashboardProfileChangePasswordRoute;
  AuthenticatedDashboardProfileHistoryRoute: typeof AuthenticatedDashboardProfileHistoryRoute;
  AuthenticatedDashboardProfileProfileRoute: typeof AuthenticatedDashboardProfileProfileRoute;
}

const AuthenticatedDashboardProfileRouteChildren: AuthenticatedDashboardProfileRouteChildren = {
  AuthenticatedDashboardProfileChangePasswordRoute:
    AuthenticatedDashboardProfileChangePasswordRoute,
  AuthenticatedDashboardProfileHistoryRoute: AuthenticatedDashboardProfileHistoryRoute,
  AuthenticatedDashboardProfileProfileRoute: AuthenticatedDashboardProfileProfileRoute,
};

const AuthenticatedDashboardProfileRouteWithChildren =
  AuthenticatedDashboardProfileRoute._addFileChildren(AuthenticatedDashboardProfileRouteChildren);

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRouteWithChildren;
  AuthenticatedDashboardContentEditorRoute: typeof AuthenticatedDashboardContentEditorRoute;
  AuthenticatedDashboardPracticeCollectionIdRoute: typeof AuthenticatedDashboardPracticeCollectionIdRoute;
  AuthenticatedDashboardPracticeIndexRoute: typeof AuthenticatedDashboardPracticeIndexRoute;
  AuthenticatedDashboardPracticeSimulatedTestResultRoute: typeof AuthenticatedDashboardPracticeSimulatedTestResultRoute;
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren = {
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRouteWithChildren,
  AuthenticatedDashboardContentEditorRoute: AuthenticatedDashboardContentEditorRoute,
  AuthenticatedDashboardPracticeCollectionIdRoute: AuthenticatedDashboardPracticeCollectionIdRoute,
  AuthenticatedDashboardPracticeIndexRoute: AuthenticatedDashboardPracticeIndexRoute,
  AuthenticatedDashboardPracticeSimulatedTestResultRoute:
    AuthenticatedDashboardPracticeSimulatedTestResultRoute,
};

const AuthenticatedDashboardRouteWithChildren = AuthenticatedDashboardRoute._addFileChildren(
  AuthenticatedDashboardRouteChildren
);

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedSpeakingIndexRoute: typeof AuthenticatedSpeakingIndexRoute;
  AuthenticatedPracticeSimulatedTestIndexRoute: typeof AuthenticatedPracticeSimulatedTestIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSpeakingIndexRoute: AuthenticatedSpeakingIndexRoute,
  AuthenticatedPracticeSimulatedTestIndexRoute: AuthenticatedPracticeSimulatedTestIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren
);

interface AuthenticationRouteChildren {
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute;
  AuthenticationLogInRoute: typeof AuthenticationLogInRoute;
  AuthenticationResetPasswordRoute: typeof AuthenticationResetPasswordRoute;
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute;
  AuthenticationVerifyOtpRoute: typeof AuthenticationVerifyOtpRoute;
}

const AuthenticationRouteChildren: AuthenticationRouteChildren = {
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationLogInRoute: AuthenticationLogInRoute,
  AuthenticationResetPasswordRoute: AuthenticationResetPasswordRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  AuthenticationVerifyOtpRoute: AuthenticationVerifyOtpRoute,
};

const AuthenticationRouteWithChildren = AuthenticationRoute._addFileChildren(
  AuthenticationRouteChildren
);

export interface FileRoutesByFullPath {
  "": typeof AuthenticatedDashboardProfileRouteWithChildren;
  "/forgot-password": typeof AuthenticationForgotPasswordRoute;
  "/log-in": typeof AuthenticationLogInRoute;
  "/reset-password": typeof AuthenticationResetPasswordRoute;
  "/sign-up": typeof AuthenticationSignUpRoute;
  "/verify-otp": typeof AuthenticationVerifyOtpRoute;
  "/": typeof AuthenticatedIndexRoute;
  "/content-editor": typeof AuthenticatedDashboardContentEditorRoute;
  "/speaking": typeof AuthenticatedSpeakingIndexRoute;
  "/change-password": typeof AuthenticatedDashboardProfileChangePasswordRoute;
  "/history": typeof AuthenticatedDashboardProfileHistoryRoute;
  "/profile": typeof AuthenticatedDashboardProfileProfileRoute;
  "/practice/$collectionId": typeof AuthenticatedDashboardPracticeCollectionIdRoute;
  "/practice": typeof AuthenticatedDashboardPracticeIndexRoute;
  "/practice/simulated-test": typeof AuthenticatedPracticeSimulatedTestIndexRoute;
  "/practice/simulated-test/result": typeof AuthenticatedDashboardPracticeSimulatedTestResultRoute;
}

export interface FileRoutesByTo {
  "": typeof AuthenticatedDashboardProfileRouteWithChildren;
  "/forgot-password": typeof AuthenticationForgotPasswordRoute;
  "/log-in": typeof AuthenticationLogInRoute;
  "/reset-password": typeof AuthenticationResetPasswordRoute;
  "/sign-up": typeof AuthenticationSignUpRoute;
  "/verify-otp": typeof AuthenticationVerifyOtpRoute;
  "/": typeof AuthenticatedIndexRoute;
  "/content-editor": typeof AuthenticatedDashboardContentEditorRoute;
  "/speaking": typeof AuthenticatedSpeakingIndexRoute;
  "/change-password": typeof AuthenticatedDashboardProfileChangePasswordRoute;
  "/history": typeof AuthenticatedDashboardProfileHistoryRoute;
  "/profile": typeof AuthenticatedDashboardProfileProfileRoute;
  "/practice/$collectionId": typeof AuthenticatedDashboardPracticeCollectionIdRoute;
  "/practice": typeof AuthenticatedDashboardPracticeIndexRoute;
  "/practice/simulated-test": typeof AuthenticatedPracticeSimulatedTestIndexRoute;
  "/practice/simulated-test/result": typeof AuthenticatedDashboardPracticeSimulatedTestResultRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_authentication": typeof AuthenticationRouteWithChildren;
  "/_authenticated/_dashboard": typeof AuthenticatedDashboardRouteWithChildren;
  "/_authentication/forgot-password": typeof AuthenticationForgotPasswordRoute;
  "/_authentication/log-in": typeof AuthenticationLogInRoute;
  "/_authentication/reset-password": typeof AuthenticationResetPasswordRoute;
  "/_authentication/sign-up": typeof AuthenticationSignUpRoute;
  "/_authentication/verify-otp": typeof AuthenticationVerifyOtpRoute;
  "/_authenticated/": typeof AuthenticatedIndexRoute;
  "/_authenticated/_dashboard/_profile": typeof AuthenticatedDashboardProfileRouteWithChildren;
  "/_authenticated/_dashboard/content-editor": typeof AuthenticatedDashboardContentEditorRoute;
  "/_authenticated/speaking/": typeof AuthenticatedSpeakingIndexRoute;
  "/_authenticated/_dashboard/_profile/change-password": typeof AuthenticatedDashboardProfileChangePasswordRoute;
  "/_authenticated/_dashboard/_profile/history": typeof AuthenticatedDashboardProfileHistoryRoute;
  "/_authenticated/_dashboard/_profile/profile": typeof AuthenticatedDashboardProfileProfileRoute;
  "/_authenticated/_dashboard/practice/$collectionId": typeof AuthenticatedDashboardPracticeCollectionIdRoute;
  "/_authenticated/_dashboard/practice/": typeof AuthenticatedDashboardPracticeIndexRoute;
  "/_authenticated/practice/simulated-test/": typeof AuthenticatedPracticeSimulatedTestIndexRoute;
  "/_authenticated/_dashboard/practice/simulated-test/result": typeof AuthenticatedDashboardPracticeSimulatedTestResultRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ""
    | "/forgot-password"
    | "/log-in"
    | "/reset-password"
    | "/sign-up"
    | "/verify-otp"
    | "/"
    | "/content-editor"
    | "/speaking"
    | "/change-password"
    | "/history"
    | "/profile"
    | "/practice/$collectionId"
    | "/practice"
    | "/practice/simulated-test"
    | "/practice/simulated-test/result";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ""
    | "/forgot-password"
    | "/log-in"
    | "/reset-password"
    | "/sign-up"
    | "/verify-otp"
    | "/"
    | "/content-editor"
    | "/speaking"
    | "/change-password"
    | "/history"
    | "/profile"
    | "/practice/$collectionId"
    | "/practice"
    | "/practice/simulated-test"
    | "/practice/simulated-test/result";
  id:
    | "__root__"
    | "/_authenticated"
    | "/_authentication"
    | "/_authenticated/_dashboard"
    | "/_authentication/forgot-password"
    | "/_authentication/log-in"
    | "/_authentication/reset-password"
    | "/_authentication/sign-up"
    | "/_authentication/verify-otp"
    | "/_authenticated/"
    | "/_authenticated/_dashboard/_profile"
    | "/_authenticated/_dashboard/content-editor"
    | "/_authenticated/speaking/"
    | "/_authenticated/_dashboard/_profile/change-password"
    | "/_authenticated/_dashboard/_profile/history"
    | "/_authenticated/_dashboard/_profile/profile"
    | "/_authenticated/_dashboard/practice/$collectionId"
    | "/_authenticated/_dashboard/practice/"
    | "/_authenticated/practice/simulated-test/"
    | "/_authenticated/_dashboard/practice/simulated-test/result";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AuthenticationRoute: typeof AuthenticationRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthenticationRoute: AuthenticationRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated",
        "/_authentication"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/_dashboard",
        "/_authenticated/",
        "/_authenticated/speaking/",
        "/_authenticated/practice/simulated-test/"
      ]
    },
    "/_authentication": {
      "filePath": "_authentication.tsx",
      "children": [
        "/_authentication/forgot-password",
        "/_authentication/log-in",
        "/_authentication/reset-password",
        "/_authentication/sign-up",
        "/_authentication/verify-otp"
      ]
    },
    "/_authenticated/_dashboard": {
      "filePath": "_authenticated/_dashboard.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/_dashboard/_profile",
        "/_authenticated/_dashboard/content-editor",
        "/_authenticated/_dashboard/practice/$collectionId",
        "/_authenticated/_dashboard/practice/",
        "/_authenticated/_dashboard/practice/simulated-test/result"
      ]
    },
    "/_authentication/forgot-password": {
      "filePath": "_authentication/forgot-password.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/log-in": {
      "filePath": "_authentication/log-in.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/reset-password": {
      "filePath": "_authentication/reset-password.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/sign-up": {
      "filePath": "_authentication/sign-up.tsx",
      "parent": "/_authentication"
    },
    "/_authentication/verify-otp": {
      "filePath": "_authentication/verify-otp.tsx",
      "parent": "/_authentication"
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_dashboard/_profile": {
      "filePath": "_authenticated/_dashboard/_profile.tsx",
      "parent": "/_authenticated/_dashboard",
      "children": [
        "/_authenticated/_dashboard/_profile/change-password",
        "/_authenticated/_dashboard/_profile/history",
        "/_authenticated/_dashboard/_profile/profile"
      ]
    },
    "/_authenticated/_dashboard/content-editor": {
      "filePath": "_authenticated/_dashboard/content-editor.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/speaking/": {
      "filePath": "_authenticated/speaking/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_dashboard/_profile/change-password": {
      "filePath": "_authenticated/_dashboard/_profile/change-password.tsx",
      "parent": "/_authenticated/_dashboard/_profile"
    },
    "/_authenticated/_dashboard/_profile/history": {
      "filePath": "_authenticated/_dashboard/_profile/history.tsx",
      "parent": "/_authenticated/_dashboard/_profile"
    },
    "/_authenticated/_dashboard/_profile/profile": {
      "filePath": "_authenticated/_dashboard/_profile/profile.tsx",
      "parent": "/_authenticated/_dashboard/_profile"
    },
    "/_authenticated/_dashboard/practice/$collectionId": {
      "filePath": "_authenticated/_dashboard/practice/$collectionId.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/_dashboard/practice/": {
      "filePath": "_authenticated/_dashboard/practice/index.tsx",
      "parent": "/_authenticated/_dashboard"
    },
    "/_authenticated/practice/simulated-test/": {
      "filePath": "_authenticated/practice/simulated-test/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/_dashboard/practice/simulated-test/result": {
      "filePath": "_authenticated/_dashboard/practice/simulated-test/result.tsx",
      "parent": "/_authenticated/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
