name: Deploy React App to DigitalOcean

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  deploy-infra:
    name: Deploy infra
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Run Terraform Environment Action
        uses: ./.github/actions/terraform-env-action
        with:
          working-directory: "./infra"
          apply: "yes"
          do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Save Droplet IP as Artifact
        run: |
          echo "$(terraform output -raw droplet_ip)" > ./droplet_ip.txt  
          cat ./droplet_ip.txt
        working-directory: "./infra"

      - name: Upload Droplet IP
        uses: actions/upload-artifact@v4
        with:
          name: droplet-ip
          path: ./infra/droplet_ip.txt

  configure-nginx:
    name: Configure Nginx
    runs-on: ubuntu-latest
    needs: deploy-infra

    environment: production

    steps:
      - uses: actions/checkout@v4

      # 🔵 Download Droplet IP from artifact
      - name: Download Droplet IP
        uses: actions/download-artifact@v4
        with:
          name: droplet-ip

      # 🔵 Setup SSH Key
      - name: Configure SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Update Nginx Configuration
        run: |
          DROPLET_IP=$(cat droplet_ip.txt)  # Read IP dynamically
          ssh -o StrictHostKeyChecking=no -i private_key.pem root@$DROPLET_IP << 'EOF'
            sudo sed -i 's/YOUR_DOMAIN_OR_IP/'"$DROPLET_IP"'/g' /etc/nginx/sites-available/default
            sudo systemctl restart nginx
          EOF

  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: configure-nginx

    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-dependencies
      - name: Download Droplet IP
        uses: actions/download-artifact@v4
        with:
          name: droplet-ip
      - name: Deploy Files to DigitalOcean
        uses: ./.github/actions/do-sync-action
