name: Infra Check
on:
  pull_request:
    branches: ["main"]

jobs:
  infra-check:
    name: Infra Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Terraform Environment Action
        uses: ./.github/actions/terraform-env-action
        with:
          working-directory: "./infra"
          apply: "no"
